export enum EVENT_REJECT_CODES {
    INVALID_MARKET = "INVALID_MARKET",
    INVALID_SIDE = "INVALID_SIDE",
    INVALID_ORDER_TYPE = "INVALID_ORDER_TYPE",
    INVALID_TIF = "INVALID_TIF",

    INVALID_QUANTITY = "INVALID_QUANTITY",
    INVALID_PRICE = "INVALID_PRICE",
    INVALID_LEVERAGE = "INVALID_LEVERAGE",

    INVALID_TICK_SIZE = "INVALID_TICK_SIZE",
    INVALID_LOT_SIZE = "INVALID_LOT_SIZE",

    BELOW_MIN_QTY = "BELOW_MIN_QTY",
    BELOW_MIN_NOTIONAL = "BELOW_MIN_NOTIONAL",

    LEVERAGE_EXCEEDED = "LEVERAGE_EXCEEDED",

    DUPLICATE_CLIENT_ORDER_ID = "DUPLICATE_CLIENT_ORDER_ID",

    POSITION_CONFLICT = "POSITION_CONFLICT",
    REDUCE_ONLY_INVALID = "REDUCE_ONLY_INVALID",

    INSUFFICIENT_MARGIN = "INSUFFICIENT_MARGIN",

    MARKET_ORDER_GTC = "MARKET_ORDER_GTC",

    POST_ONLY_WOULD_TRADE = "POST_ONLY_WOULD_TRADE",

    STP_TRIGGERED = "STP_TRIGGERED",

    MAX_OPEN_ORDERS = "MAX_OPEN_ORDERS",

    NO_LIQUIDITY = "NO_LIQUIDITY",

    NO_BALANCES = "NO_BALANCES_FOUND",
}